language: ruby
rvm:
- 2.1
script: script/build
before_script:
- ls script/.ssh
- openssl aes-256-cbc -K $encrypted_5727dd035aee_key -iv $encrypted_5727dd035aee_iv -in script/.ssh/bozo.enc -out script/.ssh/bozo -d
- chmod 600 script/.ssh/bozo
- ls -l script/.ssh
